import type { CSSProperties } from "react"
import cropsRaw from "./sprite-crops.json"

export type SpriteBox = { x: number; y: number; w: number; h: number }

// Map of web sprite path -> content bounding box (0..1 fractions of the canvas).
// Generated by scripts/audit-portrait-crops.ts (measures non-transparent pixel bounds via sharp).
const crops = cropsRaw as Record<string, SpriteBox>

export function getSpriteBox(url?: string): SpriteBox | null {
  if (!url) return null
  const clean = url.split("?")[0]
  return crops[clean] ?? null
}

/**
 * Inline style that makes a transparent-bg bust FILL its frame with the content
 * anchored to the bottom edge (character-select style) — never floating.
 *
 * The frame element must be `position:relative; overflow:hidden`. Works off the
 * measured content box; falls back to a sane bottom-anchored scale when unmeasured.
 */
export function portraitFillStyle(
  url?: string,
  opts: { targetH?: number; maxScale?: number; fit?: "height" | "width"; targetW?: number } = {},
): CSSProperties {
  const { targetH = 1.0, maxScale = 1.9, fit = "height", targetW = 0.94 } = opts
  const box = getSpriteBox(url)

  if (!box) {
    return {
      position: "absolute",
      left: "50%",
      bottom: "-3%",
      width: "126%",
      height: "auto",
      maxWidth: "none",
      transform: "translateX(-50%)",
      imageRendering: "pixelated",
    }
  }

  const cx = box.x + box.w / 2 // content centre x (fraction)
  // NOTE: in a transform list the rightmost op applies FIRST, so scale() runs
  // before these translates — distances must be pre-multiplied by the scale or
  // the content floats (scale-1)*margin short of the frame bottom (the "black
  // bar under every face" bug, owner report 2026-08-31).
  const heightScale = Math.min(maxScale, targetH / Math.max(0.15, box.h))
  const txFor = (s: number) => -(cx - 0.5) * s * 100 // re-centre content horizontally
  const tyFor = (s: number) => (1 - (box.y + box.h)) * s * 100 // content bottom -> frame bottom

  if (fit === "width") {
    // width-driven: content spans targetW of the frame width regardless of frame height —
    // right choice for tall portrait columns where height-driven fill would blow up the face
    const widthPct = Math.min(maxScale, targetW / Math.max(0.15, box.w)) * 100
    return {
      position: "absolute",
      left: "50%",
      bottom: 0,
      width: `${widthPct.toFixed(1)}%`,
      height: "auto",
      maxWidth: "none",
      transform: `translateX(-50%) translateX(${txFor(1).toFixed(2)}%) translateY(${tyFor(1).toFixed(2)}%)`,
      imageRendering: "pixelated",
    }
  }

  const scale = heightScale // fill content to targetH of frame
  return {
    position: "absolute",
    left: "50%",
    bottom: 0,
    height: "100%",
    width: "auto",
    maxWidth: "none",
    transformOrigin: "bottom center",
    transform: `translateX(-50%) translateX(${txFor(scale).toFixed(2)}%) translateY(${tyFor(scale).toFixed(2)}%) scale(${scale.toFixed(3)})`,
    imageRendering: "pixelated",
  }
}
