export type BadgeRarity = "common" | "rare" | "epic" | "legendary"
export type BadgeCategory =
  | "writing"
  | "performance"
  | "reputation"
  | "content_style"
  | "regional"
  | "tournament"
  | "special_ability"
  | "city"
  | "region"
  | "milestone"

export interface Badge {
  id: string
  name: string
  description: string
  fullEffectText: string
  rarity: BadgeRarity
  category: BadgeCategory
  icon: string
  imageId: number | null
  effects: {
    lyricism?: number
    wordplay?: number
    creativity?: number
    flow?: number
    stagePresence?: number
    crowdControl?: number
    delivery?: number
    consistency?: number
    adaptability?: number
    resilience?: number
    chokeRisk?: number
    stressPerDay?: number
    earningsBonus?: number
    fanGrowth?: number
    crowdReaction?: number
    selfAwareness?: number // Affects accuracy of perceived readiness
  }
  isNegative?: boolean
  removable?: boolean
  removalCondition?: string
  prepEffects?: PrepEffects
}

export interface PrepEffects {
  researchEfficiency?: number
  writingEfficiency?: number
  rehearsalEfficiency?: number
  restEfficiency?: number
  segmentsPerDay?: number
  activitiesPerDay?: number
  lowPrepBonus?: number
  highPrepBonus?: number
  minPrepDays?: number
  canFreestyle?: boolean
  noMultiBattleStress?: boolean
}

export const ALL_BADGES: Badge[] = [
  // WRITING BADGES (20)
  {
    id: "master_wordsmith",
    name: "MASTER WORDSMITH",
    description: "Exceptional wordplay and double entendres that captivate judges",
    fullEffectText: "Exceptional wordplay and double entendres that captivate judges",
    rarity: "legendary",
    category: "writing",
    icon: "👑",
    imageId: null,
    effects: { wordplay: 15, creativity: 10 },
  },
  {
    id: "punchline_king",
    name: "PUNCHLINE KING",
    description: "Devastating punchlines that leave crowds speechless",
    fullEffectText: "Devastating punchlines with perfect timing that devastate opponents",
    rarity: "legendary",
    category: "writing",
    icon: "🥊",
    imageId: null,
    effects: { wordplay: 15, crowdReaction: 10, creativity: 5 },
  },
  {
    id: "technical_writer",
    name: "TECHNICAL WRITER",
    description: "Complex schemes and intricate rhyme patterns",
    fullEffectText: "Master of complex rhyme schemes and intricate patterns",
    rarity: "epic",
    category: "writing",
    icon: "📝",
    imageId: null,
    effects: { lyricism: 12, wordplay: 8 },
  },
  {
    id: "angle_assassin",
    name: "ANGLE ASSASSIN",
    description: "Unique angles and unexpected approaches",
    fullEffectText: "Finds unique angles and unexpected approaches that surprise judges",
    rarity: "rare",
    category: "writing",
    icon: "🎯",
    imageId: null,
    effects: { creativity: 10, wordplay: 5 },
  },
  {
    id: "scheme_specialist",
    name: "SCHEME SPECIALIST",
    description: "Multi-layered schemes that impress judges",
    fullEffectText: "Creates multi-layered rhyme schemes",
    rarity: "rare",
    category: "writing",
    icon: "🧩",
    imageId: null,
    effects: { lyricism: 10, creativity: 5 },
  },
  {
    id: "metaphor_master",
    name: "METAPHOR MASTER",
    description: "Creative comparisons and vivid imagery",
    fullEffectText: "Crafts vivid metaphors and creative comparisons",
    rarity: "rare",
    category: "writing",
    icon: "🎨",
    imageId: null,
    effects: { creativity: 10, lyricism: 5 },
  },
  {
    id: "rebuttal_king",
    name: "REBUTTAL KING",
    description: "Quick wit and effective rebuttals",
    fullEffectText: "Expert at crafting devastating rebuttals",
    rarity: "epic",
    category: "writing",
    icon: "⚔️",
    imageId: 46,
    effects: { adaptability: 12, wordplay: 8 },
  },
  {
    id: "well_researched",
    name: "WELL RESEARCHED",
    description: "Thorough preparation shows in material quality",
    fullEffectText: "Extensive research leads to well-crafted material",
    rarity: "common",
    category: "writing",
    icon: "🔍",
    imageId: 54,
    effects: { lyricism: 5, wordplay: 5 },
  },
  {
    id: "storyteller",
    name: "STORYTELLER",
    description: "Narrative-driven rounds that engage audiences",
    fullEffectText: "Weaves compelling narratives through battle rounds",
    rarity: "rare",
    category: "writing",
    icon: "📖",
    imageId: null,
    effects: { creativity: 8, crowdReaction: 7 },
  },
  {
    id: "bar_god",
    name: "BAR GOD",
    description: "Consistently delivers quotable bars",
    fullEffectText: "Every line is quotable and memorable",
    rarity: "legendary",
    category: "writing",
    icon: "⭐",
    imageId: null,
    effects: { lyricism: 15, wordplay: 12, crowdReaction: 8 },
  },
  {
    id: "multi_syllabic",
    name: "MULTI-SYLLABIC MASTER",
    description: "Complex multi-syllable rhyme schemes",
    fullEffectText: "Master of multi-syllabic rhyme patterns",
    rarity: "epic",
    category: "writing",
    icon: "🎼",
    imageId: null,
    effects: { lyricism: 12, wordplay: 6 },
  },
  {
    id: "haymaker_specialist",
    name: "HAYMAKER SPECIALIST",
    description: "Delivers knockout punchlines consistently",
    fullEffectText: "Specializes in devastating haymaker punchlines",
    rarity: "epic",
    category: "writing",
    icon: "💥",
    imageId: null,
    effects: { wordplay: 10, crowdReaction: 12 },
  },
  {
    id: "wordsmith",
    name: "WORDSMITH",
    description: "Strong vocabulary and word choice",
    fullEffectText: "Excellent command of vocabulary and word selection",
    rarity: "common",
    category: "writing",
    icon: "📚",
    imageId: null,
    effects: { lyricism: 7, wordplay: 3 },
  },
  {
    id: "clever_writer",
    name: "CLEVER WRITER",
    description: "Smart wordplay and witty bars",
    fullEffectText: "Consistently clever wordplay and witty observations",
    rarity: "rare",
    category: "writing",
    icon: "🧠",
    imageId: null,
    effects: { wordplay: 10, creativity: 5 },
  },
  {
    id: "quotable",
    name: "QUOTABLE",
    description: "Lines get repeated by fans",
    fullEffectText: "Creates memorable quotable moments",
    rarity: "rare",
    category: "writing",
    icon: "💬",
    imageId: null,
    effects: { wordplay: 8, fanGrowth: 10 },
  },
  {
    id: "layered_writer",
    name: "LAYERED WRITER",
    description: "Multiple meanings in every bar",
    fullEffectText: "Packs multiple meanings into every line",
    rarity: "epic",
    category: "writing",
    icon: "🎭",
    imageId: null,
    effects: { lyricism: 10, wordplay: 10 },
  },
  {
    id: "pocket_checker",
    name: "POCKET CHECKER",
    description: "Personal angles that hit hard",
    fullEffectText: "Finds personal angles that really resonate",
    rarity: "rare",
    category: "writing",
    icon: "🎯",
    imageId: null,
    effects: { creativity: 10, crowdReaction: 8 },
  },
  {
    id: "flip_master",
    name: "FLIP MASTER",
    description: "Turns opponent's bars against them",
    fullEffectText: "Expert at flipping opponent's material",
    rarity: "epic",
    category: "writing",
    icon: "🔄",
    imageId: null,
    effects: { adaptability: 15, wordplay: 5 },
  },
  {
    id: "structure_savant",
    name: "STRUCTURE SAVANT",
    description: "Perfect round structure and flow",
    fullEffectText: "Masterful round structure and organization",
    rarity: "rare",
    category: "writing",
    icon: "🏗️",
    imageId: null,
    effects: { flow: 10, lyricism: 5 },
  },
  {
    id: "versatile_writer",
    name: "VERSATILE WRITER",
    description: "Adapts writing style to any opponent",
    fullEffectText: "Can adapt writing style to match any situation",
    rarity: "epic",
    category: "writing",
    icon: "🎪",
    imageId: null,
    effects: { adaptability: 12, creativity: 8 },
  },

  // PERFORMANCE BADGES (20)
  {
    id: "crowd_favorite",
    name: "CROWD FAVORITE",
    description: "Consistently wins over audiences",
    fullEffectText: "Natural ability to win over any crowd",
    rarity: "epic",
    category: "performance",
    icon: "❤️",
    imageId: null,
    effects: { crowdControl: 15, stagePresence: 5 },
  },
  {
    id: "showman",
    name: "SHOWMAN",
    description: "Commands attention with stage presence",
    fullEffectText: "Theatrical performance that commands attention",
    rarity: "rare",
    category: "performance",
    icon: "🎭",
    imageId: null,
    effects: { stagePresence: 12, delivery: 5 },
  },
  {
    id: "energy_master",
    name: "ENERGY MASTER",
    description: "Maintains high energy throughout",
    fullEffectText: "Sustains explosive energy for entire performance",
    rarity: "epic",
    category: "performance",
    icon: "⚡",
    imageId: null,
    effects: { delivery: 12, stagePresence: 8 },
  },
  {
    id: "vocal_presence",
    name: "VOCAL PRESENCE",
    description: "Powerful voice projection",
    fullEffectText: "Commanding vocal presence that fills the venue",
    rarity: "rare",
    category: "performance",
    icon: "🎤",
    imageId: null,
    effects: { delivery: 10, crowdControl: 5 },
  },
  {
    id: "ring_general",
    name: "RING GENERAL",
    description: "Controls the pace and atmosphere",
    fullEffectText: "Total control of battle pace and atmosphere",
    rarity: "legendary",
    category: "performance",
    icon: "👑",
    imageId: null,
    effects: { crowdControl: 15, stagePresence: 10 },
  },
  {
    id: "aggressive_performer",
    name: "AGGRESSIVE PERFORMER",
    description: "Intense, in-your-face delivery",
    fullEffectText: "Relentlessly aggressive performance style",
    rarity: "rare",
    category: "performance",
    icon: "🔥",
    imageId: null,
    effects: { delivery: 12, stagePresence: 5 },
  },
  {
    id: "crowd_reader",
    name: "CROWD READER",
    description: "Reads and adapts to crowd energy",
    fullEffectText: "Intuitively reads and adapts to crowd reactions",
    rarity: "epic",
    category: "performance",
    icon: "👥",
    imageId: null,
    effects: { crowdControl: 12, adaptability: 8 },
  },
  {
    id: "composed",
    name: "COMPOSED",
    description: "Never rattled under pressure",
    fullEffectText: "Maintains composure in high-pressure situations",
    rarity: "rare",
    category: "performance",
    icon: "🧘",
    imageId: null,
    effects: { consistency: 10, chokeRisk: -15 },
  },
  {
    id: "animated",
    name: "ANIMATED",
    description: "Expressive facial expressions and gestures",
    fullEffectText: "Dynamic facial expressions and gestures enhance performance",
    rarity: "common",
    category: "performance",
    icon: "😄",
    imageId: null,
    effects: { stagePresence: 8, crowdReaction: 5 },
  },
  {
    id: "intimidator",
    name: "INTIMIDATOR",
    description: "Physical presence unsettles opponents",
    fullEffectText: "Imposing presence that intimidates opponents",
    rarity: "rare",
    category: "performance",
    icon: "😤",
    imageId: null,
    effects: { stagePresence: 10, delivery: 7 },
  },
  {
    id: "mic_control",
    name: "MIC CONTROL",
    description: "Perfect microphone technique",
    fullEffectText: "Masterful microphone control and technique",
    rarity: "common",
    category: "performance",
    icon: "🎙️",
    imageId: null,
    effects: { delivery: 8 },
  },
  {
    id: "stage_veteran",
    name: "STAGE VETERAN",
    description: "Experience shows in performance",
    fullEffectText: "Years of experience result in polished performance",
    rarity: "epic",
    category: "performance",
    icon: "🎖️",
    imageId: null,
    effects: { stagePresence: 10, consistency: 10 },
  },
  {
    id: "crowd_hyper",
    name: "CROWD HYPER",
    description: "Gets crowds extremely hyped",
    fullEffectText: "Ability to send crowds into a frenzy",
    rarity: "legendary",
    category: "performance",
    icon: "🎉",
    imageId: null,
    effects: { crowdControl: 15, crowdReaction: 15 },
  },
  {
    id: "charismatic",
    name: "CHARISMATIC",
    description: "Natural charisma draws people in",
    fullEffectText: "Magnetic charisma that draws in audiences",
    rarity: "rare",
    category: "performance",
    icon: "✨",
    imageId: null,
    effects: { stagePresence: 10, fanGrowth: 8 },
  },
  {
    id: "tempo_master",
    name: "TEMPO MASTER",
    description: "Perfect control of delivery pace",
    fullEffectText: "Masterful control of tempo and pacing",
    rarity: "epic",
    category: "performance",
    icon: "⏱️",
    imageId: null,
    effects: { flow: 12, delivery: 8 },
  },
  {
    id: "physical_performer",
    name: "PHYSICAL PERFORMER",
    description: "Uses body language effectively",
    fullEffectText: "Effective use of physical movement and gestures",
    rarity: "rare",
    category: "performance",
    icon: "🕺",
    imageId: null,
    effects: { stagePresence: 10, delivery: 5 },
  },
  {
    id: "voice_modulator",
    name: "VOICE MODULATOR",
    description: "Dynamic vocal range and inflection",
    fullEffectText: "Uses vocal variety to enhance delivery",
    rarity: "rare",
    category: "performance",
    icon: "🎵",
    imageId: null,
    effects: { delivery: 12 },
  },
  {
    id: "crowd_silencer",
    name: "CROWD SILENCER",
    description: "Lines so good they silence the room",
    fullEffectText: "Drops bars so heavy they silence entire venues",
    rarity: "legendary",
    category: "performance",
    icon: "🤫",
    imageId: null,
    effects: { wordplay: 10, crowdReaction: 15 },
  },
  {
    id: "camera_aware",
    name: "CAMERA AWARE",
    description: "Performs well for cameras and judges",
    fullEffectText: "Naturally camera-ready performance",
    rarity: "common",
    category: "performance",
    icon: "📹",
    imageId: null,
    effects: { stagePresence: 5, delivery: 5 },
  },
  {
    id: "moment_maker",
    name: "MOMENT MAKER",
    description: "Creates viral moments",
    fullEffectText: "Consistently creates viral-worthy moments",
    rarity: "epic",
    category: "performance",
    icon: "🌟",
    imageId: null,
    effects: { crowdReaction: 12, fanGrowth: 15 },
  },

  // REPUTATION BADGES (15)
  {
    id: "rising_star",
    name: "RISING STAR",
    description: "Quickly gaining recognition",
    fullEffectText: "Rapidly rising through the ranks",
    rarity: "common",
    category: "reputation",
    icon: "⭐",
    imageId: null,
    effects: { fanGrowth: 15 },
  },
  {
    id: "street_legend",
    name: "STREET LEGEND",
    description: "Respected in underground circles",
    fullEffectText: "Legendary status in underground scene",
    rarity: "epic",
    category: "reputation",
    icon: "🏆",
    imageId: null,
    effects: { fanGrowth: 10, earningsBonus: 15 },
  },
  {
    id: "main_stage_ready",
    name: "MAIN STAGE READY",
    description: "Proven on big stages",
    fullEffectText: "Ready for the biggest stages",
    rarity: "rare",
    category: "reputation",
    icon: "🎪",
    imageId: null,
    effects: { stagePresence: 8, consistency: 7 },
  },
  {
    id: "respected_veteran",
    name: "RESPECTED VETERAN",
    description: "Years of consistent performance",
    fullEffectText: "Earned respect through years of excellence",
    rarity: "epic",
    category: "reputation",
    icon: "👴",
    imageId: null,
    effects: { consistency: 12, fanGrowth: 8 },
  },
  {
    id: "hype_machine",
    name: "HYPE MACHINE",
    description: "Generates massive buzz",
    fullEffectText: "Creates hype wherever you go",
    rarity: "rare",
    category: "reputation",
    icon: "📢",
    imageId: null,
    effects: { fanGrowth: 20 },
  },
  {
    id: "underdog",
    name: "UNDERDOG",
    description: "Thrives when underestimated",
    fullEffectText: "Performs best when counted out",
    rarity: "rare",
    category: "reputation",
    icon: "🐕",
    imageId: null,
    effects: { adaptability: 10, crowdReaction: 8 },
  },
  {
    id: "controversial",
    name: "CONTROVERSIAL",
    description: "Generates buzz good or bad",
    fullEffectText: "Controversial style generates attention",
    rarity: "rare",
    category: "reputation",
    icon: "⚠️",
    imageId: null,
    effects: { fanGrowth: 15, stressPerDay: 2 },
  },
  {
    id: "fan_favorite",
    name: "FAN FAVORITE",
    description: "Beloved by the community",
    fullEffectText: "Universally loved by battle rap fans",
    rarity: "epic",
    category: "reputation",
    icon: "💖",
    imageId: null,
    effects: { fanGrowth: 15, earningsBonus: 10 },
  },
  {
    id: "gatekeeper",
    name: "GATEKEEPER",
    description: "Tests rising battlers",
    fullEffectText: "The test for any rising battler",
    rarity: "epic",
    category: "reputation",
    icon: "🚪",
    imageId: null,
    effects: { consistency: 10, earningsBonus: 8 },
  },
  {
    id: "draw_power",
    name: "DRAW POWER",
    description: "Brings in big crowds",
    fullEffectText: "Name alone sells out venues",
    rarity: "legendary",
    category: "reputation",
    icon: "🎫",
    imageId: null,
    effects: { fanGrowth: 20, earningsBonus: 25 },
  },
  {
    id: "viral_battler",
    name: "VIRAL BATTLER",
    description: "Clips go viral regularly",
    fullEffectText: "Consistently produces viral moments",
    rarity: "epic",
    category: "reputation",
    icon: "📱",
    imageId: null,
    effects: { fanGrowth: 18, earningsBonus: 12 },
  },
  {
    id: "consistent_performer",
    name: "CONSISTENT PERFORMER",
    description: "Reliable quality every time",
    fullEffectText: "Never disappoints, always delivers",
    rarity: "rare",
    category: "reputation",
    icon: "📊",
    imageId: null,
    effects: { consistency: 15 },
  },
  {
    id: "headline_maker",
    name: "HEADLINE MAKER",
    description: "Always in the news",
    fullEffectText: "Name stays in headlines",
    rarity: "epic",
    category: "reputation",
    icon: "📰",
    imageId: null,
    effects: { fanGrowth: 15, stressPerDay: 1 },
  },
  {
    id: "peoples_champ",
    name: "PEOPLE'S CHAMPION",
    description: "Champion of the fans",
    fullEffectText: "The people's choice for greatest battler",
    rarity: "legendary",
    category: "reputation",
    icon: "👑",
    imageId: null,
    effects: { fanGrowth: 25, crowdReaction: 15, earningsBonus: 20 },
  },
  {
    id: "underrated",
    name: "UNDERRATED",
    description: "Skill exceeds recognition",
    fullEffectText: "Talent far exceeds current reputation",
    rarity: "common",
    category: "reputation",
    icon: "💎",
    imageId: null,
    effects: { adaptability: 8 },
  },

  // CONTENT STYLE BADGES (15)
  {
    id: "aggressive_style",
    name: "AGGRESSIVE STYLE",
    description: "In-your-face, confrontational approach",
    fullEffectText: "Relentlessly aggressive battle style",
    rarity: "common",
    category: "content_style",
    icon: "😤",
    imageId: null,
    effects: { delivery: 8, stagePresence: 7 },
  },
  {
    id: "lyrical_purist",
    name: "LYRICAL PURIST",
    description: "Focus on pure lyricism",
    fullEffectText: "Purist approach focused on lyrical excellence",
    rarity: "rare",
    category: "content_style",
    icon: "📖",
    imageId: null,
    effects: { lyricism: 12, wordplay: 8 },
  },
  {
    id: "entertainer",
    name: "ENTERTAINER",
    description: "Prioritizes entertainment value",
    fullEffectText: "Entertainment over everything",
    rarity: "rare",
    category: "content_style",
    icon: "🎪",
    imageId: null,
    effects: { stagePresence: 10, crowdReaction: 10 },
  },
  {
    id: "personals_specialist",
    name: "PERSONALS SPECIALIST",
    description: "Focus on personal attacks",
    fullEffectText: "Specializes in deeply personal material",
    rarity: "rare",
    category: "content_style",
    icon: "🎯",
    imageId: null,
    effects: { creativity: 10, crowdReaction: 8, stressPerDay: 1 },
  },
  {
    id: "freestyle_artist",
    name: "FREESTYLE ARTIST",
    description: "Incorporates freestyle elements",
    fullEffectText: "Blends written with off-the-top freestyle",
    rarity: "epic",
    category: "content_style",
    icon: "🎤",
    imageId: null,
    effects: { adaptability: 15, wordplay: 5 },
  },
  {
    id: "gun_bar_specialist",
    name: "GUN BAR SPECIALIST",
    description: "Master of weapon metaphors",
    fullEffectText: "Unmatched gun bar creativity",
    rarity: "rare",
    category: "content_style",
    icon: "🔫",
    imageId: null,
    effects: { wordplay: 10, creativity: 7 },
  },
  {
    id: "comedy_battler",
    name: "COMEDY BATTLER",
    description: "Humorous approach to battling",
    fullEffectText: "Uses humor as primary weapon",
    rarity: "rare",
    category: "content_style",
    icon: "😂",
    imageId: null,
    effects: { creativity: 10, crowdReaction: 12 },
  },
  {
    id: "shock_value",
    name: "SHOCK VALUE",
    description: "Controversial shocking content",
    fullEffectText: "Uses shock factor to get reactions",
    rarity: "rare",
    category: "content_style",
    icon: "⚡",
    imageId: null,
    effects: { crowdReaction: 12, stressPerDay: 2 },
  },
  {
    id: "sports_bars",
    name: "SPORTS BARS KING",
    description: "Sports metaphors and references",
    fullEffectText: "Master of sports metaphors and comparisons",
    rarity: "common",
    category: "content_style",
    icon: "⚽",
    imageId: null,
    effects: { wordplay: 7, creativity: 5 },
  },
  {
    id: "pop_culture",
    name: "POP CULTURE MASTER",
    description: "References resonate with audiences",
    fullEffectText: "Expertly weaves pop culture into material",
    rarity: "common",
    category: "content_style",
    icon: "🎬",
    imageId: null,
    effects: { creativity: 7, crowdReaction: 8 },
  },
  {
    id: "battle_rapper",
    name: "TRADITIONAL BATTLE RAPPER",
    description: "Classic battle rap style",
    fullEffectText: "Embodies traditional battle rap values",
    rarity: "common",
    category: "content_style",
    icon: "🎤",
    imageId: null,
    effects: { consistency: 8 },
  },
  {
    id: "poet",
    name: "POET",
    description: "Poetic and artistic approach",
    fullEffectText: "Brings poetic artistry to battle rap",
    rarity: "rare",
    category: "content_style",
    icon: "✍️",
    imageId: null,
    effects: { lyricism: 10, creativity: 8 },
  },
  {
    id: "conscious_battler",
    name: "CONSCIOUS BATTLER",
    description: "Socially aware content",
    fullEffectText: "Incorporates social consciousness into battles",
    rarity: "rare",
    category: "content_style",
    icon: "🧠",
    imageId: null,
    effects: { creativity: 8, lyricism: 7 },
  },
  {
    id: "actor",
    name: "ACTOR",
    description: "Theatrical performance style",
    fullEffectText: "Brings theatrical acting to performances",
    rarity: "rare",
    category: "content_style",
    icon: "🎭",
    imageId: null,
    effects: { stagePresence: 12, delivery: 5 },
  },
  {
    id: "street_battler",
    name: "STREET BATTLER",
    description: "Raw street battle energy",
    fullEffectText: "Brings authentic street battle energy",
    rarity: "common",
    category: "content_style",
    icon: "🏙️",
    imageId: null,
    effects: { delivery: 8, stagePresence: 5 },
  },

  // MILESTONE BADGES (10)
  {
    id: "rookie",
    name: "ROOKIE",
    description: "First 5 battles completed",
    fullEffectText: "Completed first 5 professional battles",
    rarity: "common",
    category: "milestone",
    icon: "🎓",
    imageId: null,
    effects: {},
  },
  {
    id: "journeyman",
    name: "JOURNEYMAN",
    description: "25 battles completed",
    fullEffectText: "Veteran of 25 professional battles",
    rarity: "rare",
    category: "milestone",
    icon: "🛤️",
    imageId: null,
    effects: { consistency: 5 },
  },
  {
    id: "veteran",
    name: "VETERAN",
    description: "50 battles completed",
    fullEffectText: "50+ battle veteran",
    rarity: "epic",
    category: "milestone",
    icon: "🎖️",
    imageId: null,
    effects: { consistency: 10, chokeRisk: -10 },
  },
  {
    id: "legend",
    name: "LEGEND",
    description: "100 battles completed",
    fullEffectText: "Legendary 100+ battle career",
    rarity: "legendary",
    category: "milestone",
    icon: "👑",
    imageId: null,
    effects: { consistency: 15, chokeRisk: -15, earningsBonus: 10 },
  },
  {
    id: "first_win",
    name: "FIRST VICTORY",
    description: "Won your first battle",
    fullEffectText: "First professional battle victory",
    rarity: "common",
    category: "milestone",
    icon: "🏆",
    imageId: null,
    effects: {},
  },
  {
    id: "ten_wins",
    name: "TEN VICTORIES",
    description: "10 battle wins",
    fullEffectText: "Achieved 10 battle victories",
    rarity: "common",
    category: "milestone",
    icon: "🔟",
    imageId: null,
    effects: { consistency: 3 },
  },
  {
    id: "undefeated_streak",
    name: "UNDEFEATED",
    description: "5+ win streak",
    fullEffectText: "Currently on 5+ win streak",
    rarity: "rare",
    category: "milestone",
    icon: "🔥",
    imageId: null,
    effects: { consistency: 8, fanGrowth: 10 },
  },
  {
    id: "bounce_back",
    name: "BOUNCE BACK",
    description: "Won after 3+ losses",
    fullEffectText: "Bounced back from 3+ consecutive losses",
    rarity: "common",
    category: "milestone",
    icon: "↗️",
    imageId: null,
    effects: { resilience: 5 },
  },
  {
    id: "money_maker",
    name: "MONEY MAKER",
    description: "Earned $100K+ in career",
    fullEffectText: "Earned over $100,000 in battle rap career",
    rarity: "epic",
    category: "milestone",
    icon: "💰",
    imageId: null,
    effects: { earningsBonus: 15 },
  },
  {
    id: "world_traveler",
    name: "WORLD TRAVELER",
    description: "Battled in 10+ cities",
    fullEffectText: "Battled in 10 different cities",
    rarity: "rare",
    category: "milestone",
    icon: "🌎",
    imageId: null,
    effects: { adaptability: 10 },
  },

  // CITY BADGES (5 examples - can add all cities)
  {
    id: "new_york_king",
    name: "NEW YORK KING",
    description: "Dominated NYC battle scene",
    fullEffectText: "King of New York battle rap",
    rarity: "epic",
    category: "city",
    icon: "🗽",
    imageId: null,
    effects: { fanGrowth: 15, earningsBonus: 10 },
  },
  {
    id: "la_legend",
    name: "LA LEGEND",
    description: "Los Angeles battle rap icon",
    fullEffectText: "Legendary status in LA battle scene",
    rarity: "epic",
    category: "city",
    icon: "🌴",
    imageId: null,
    effects: { fanGrowth: 15, earningsBonus: 10 },
  },
  {
    id: "chicago_champion",
    name: "CHICAGO CHAMPION",
    description: "Chicago battle rap champion",
    fullEffectText: "Champion of Chicago battle scene",
    rarity: "epic",
    category: "city",
    icon: "🏙️",
    imageId: null,
    effects: { fanGrowth: 15, earningsBonus: 10 },
  },
  {
    id: "atlanta_ace",
    name: "ATLANTA ACE",
    description: "Top of Atlanta battle scene",
    fullEffectText: "Ace of Atlanta battle rap",
    rarity: "epic",
    category: "city",
    icon: "🍑",
    imageId: null,
    effects: { fanGrowth: 15, earningsBonus: 10 },
  },
  {
    id: "detroit_destroyer",
    name: "DETROIT DESTROYER",
    description: "Detroit battle rap destroyer",
    fullEffectText: "Destroyer of Detroit battle scene",
    rarity: "epic",
    category: "city",
    icon: "🚗",
    imageId: null,
    effects: { fanGrowth: 15, earningsBonus: 10 },
  },

  // REGION BADGES (5)
  {
    id: "east_coast_elite",
    name: "EAST COAST ELITE",
    description: "Dominated East Coast scene",
    fullEffectText: "Elite status across entire East Coast",
    rarity: "legendary",
    category: "region",
    icon: "⭐",
    imageId: null,
    effects: { fanGrowth: 20, earningsBonus: 15 },
  },
  {
    id: "west_coast_warrior",
    name: "WEST COAST WARRIOR",
    description: "West Coast battle rap warrior",
    fullEffectText: "Warrior of the West Coast scene",
    rarity: "legendary",
    category: "region",
    icon: "🌊",
    imageId: null,
    effects: { fanGrowth: 20, earningsBonus: 15 },
  },
  {
    id: "midwest_monster",
    name: "MIDWEST MONSTER",
    description: "Monster of Midwest battle scene",
    fullEffectText: "Dominant force in Midwest battles",
    rarity: "legendary",
    category: "region",
    icon: "🌾",
    imageId: null,
    effects: { fanGrowth: 20, earningsBonus: 15 },
  },
  {
    id: "south_sovereign",
    name: "SOUTH SOVEREIGN",
    description: "Ruler of Southern battle scene",
    fullEffectText: "Sovereign of the South",
    rarity: "legendary",
    category: "region",
    icon: "👑",
    imageId: null,
    effects: { fanGrowth: 20, earningsBonus: 15 },
  },
  {
    id: "national_threat",
    name: "NATIONAL THREAT",
    description: "Threat in every region",
    fullEffectText: "Recognized threat nationwide",
    rarity: "legendary",
    category: "region",
    icon: "🇺🇸",
    imageId: null,
    effects: { fanGrowth: 25, earningsBonus: 20, consistency: 10 },
  },

  // NEGATIVE/REMOVABLE BADGES (10)
  {
    id: "choker",
    name: "CHOKER",
    description: "Forgot lines in recent battle",
    fullEffectText: "Recent history of forgetting lines",
    rarity: "common",
    category: "special_ability",
    icon: "😰",
    imageId: null,
    effects: { chokeRisk: 25, consistency: -10 },
    isNegative: true,
    removable: true,
    removalCondition: "Complete 3 battles without choking",
  },
  {
    id: "ring_rust",
    name: "RING RUST",
    description: "Been inactive for too long",
    fullEffectText: "Long layoff has caused ring rust",
    rarity: "common",
    category: "special_ability",
    icon: "🦀",
    imageId: null,
    effects: { consistency: -15, stagePresence: -10 },
    isNegative: true,
    removable: true,
    removalCondition: "Complete 2 battles",
  },
  {
    id: "controversial_loss",
    name: "CONTROVERSIAL LOSS",
    description: "Recent debatable loss",
    fullEffectText: "Coming off controversial decision",
    rarity: "common",
    category: "special_ability",
    icon: "⚖️",
    imageId: null,
    effects: { stressPerDay: 3 },
    isNegative: true,
    removable: true,
    removalCondition: "Win next battle clearly",
  },
  {
    id: "exposed",
    name: "EXPOSED",
    description: "Opponent found your weakness",
    fullEffectText: "Recent battle exposed weaknesses",
    rarity: "rare",
    category: "special_ability",
    icon: "🔍",
    imageId: null,
    effects: { consistency: -12, adaptability: -8 },
    isNegative: true,
    removable: true,
    removalCondition: "Win 2 battles",
  },
  {
    id: "overhyped",
    name: "OVERHYPED",
    description: "Can't live up to expectations",
    fullEffectText: "Struggling to meet high expectations",
    rarity: "rare",
    category: "special_ability",
    icon: "📉",
    imageId: null,
    effects: { stressPerDay: 4, chokeRisk: 15 },
    isNegative: true,
    removable: true,
    removalCondition: "Win 3 battles against top opponents",
  },
  {
    id: "slumping",
    name: "SLUMPING",
    description: "Performance has declined",
    fullEffectText: "Currently in a performance slump",
    rarity: "common",
    category: "special_ability",
    icon: "📉",
    imageId: null,
    effects: { consistency: -10, lyricism: -5 },
    isNegative: true,
    removable: true,
    removalCondition: "Win 2 battles convincingly",
  },
  {
    id: "beef_distracted",
    name: "BEEF DISTRACTED",
    description: "Outside beef affecting focus",
    fullEffectText: "Personal beef is distracting",
    rarity: "common",
    category: "special_ability",
    icon: "🥩",
    imageId: null,
    effects: { consistency: -8, stressPerDay: 2 },
    isNegative: true,
    removable: true,
    removalCondition: "Settle the beef or win 2 battles",
  },
  {
    id: "injured",
    name: "INJURED",
    description: "Fighting through injury",
    fullEffectText: "Battling while injured",
    rarity: "rare",
    category: "special_ability",
    icon: "🤕",
    imageId: null,
    effects: { stagePresence: -10, delivery: -8, resilience: -5 },
    isNegative: true,
    removable: true,
    removalCondition: "Rest for 2 weeks",
  },
  {
    id: "burned_out",
    name: "BURNED OUT",
    description: "Too many battles too quickly",
    fullEffectText: "Burned out from overwork",
    rarity: "rare",
    category: "special_ability",
    icon: "🔥",
    imageId: null,
    effects: { creativity: -10, consistency: -10, stressPerDay: 3 },
    isNegative: true,
    removable: true,
    removalCondition: "Take 3 weeks off",
  },
  {
    id: "predictable",
    name: "PREDICTABLE",
    description: "Style has become stale",
    fullEffectText: "Style has become too predictable",
    rarity: "common",
    category: "special_ability",
    icon: "📋",
    imageId: null,
    effects: { creativity: -12, crowdReaction: -8 },
    isNegative: true,
    removable: true,
    removalCondition: "Change prep focus for 2 battles",
  },

  // SPECIAL ABILITY - PREP BADGES (6 new)
  {
    id: "photographic_memory",
    name: "PHOTOGRAPHIC MEMORY",
    description: "Memorizes material quickly, needs less research time",
    fullEffectText: "-25% research time needed. Memorization bonus reduces rehearsal time.",
    rarity: "epic",
    category: "special_ability",
    icon: "🧠",
    imageId: null,
    effects: { consistency: 10, chokeRisk: -10 },
    prepEffects: {
      researchEfficiency: 25,
      rehearsalEfficiency: 15,
    },
  },
  {
    id: "quick_writer",
    name: "QUICK WRITER",
    description: "Writes bars faster than most battlers",
    fullEffectText: "+40% writing speed. Can write 2 segments per writing day.",
    rarity: "epic",
    category: "special_ability",
    icon: "⚡",
    imageId: null,
    effects: { lyricism: 8, creativity: 5 },
    prepEffects: {
      writingEfficiency: 40,
      segmentsPerDay: 2,
    },
  },
  {
    id: "double_shift",
    name: "DOUBLE SHIFT",
    description: "Can do two prep activities in one day",
    fullEffectText: "Can do TWO prep activities in one day. Increases stress slightly.",
    rarity: "legendary",
    category: "special_ability",
    icon: "⏰",
    imageId: null,
    effects: { stressPerDay: 2 },
    prepEffects: {
      activitiesPerDay: 2,
    },
  },
  {
    id: "team_player",
    name: "TEAM PLAYER",
    description: "Works well with crew, faster writing with support",
    fullEffectText: "+20% writing speed when on a team. Crew helps with research.",
    rarity: "rare",
    category: "special_ability",
    icon: "👥",
    imageId: null,
    effects: { resilience: 5 },
    prepEffects: {
      writingEfficiency: 20,
      researchEfficiency: 10,
    },
  },
  {
    id: "last_minute_larry",
    name: "LAST MINUTE LARRY",
    description: "Thrives under pressure with minimal prep time",
    fullEffectText: "+30% effectiveness with less than 3 prep days. Works best under pressure.",
    rarity: "epic",
    category: "special_ability",
    icon: "🏃",
    imageId: null,
    effects: { adaptability: 15, chokeRisk: 5 },
    prepEffects: {
      lowPrepBonus: 30,
      minPrepDays: 3,
    },
  },
  {
    id: "preparation_monster",
    name: "PREPARATION MONSTER",
    description: "Maximizes long prep windows like a champion",
    fullEffectText: "+50% effectiveness with 10+ prep days. The longer the prep, the deadlier.",
    rarity: "legendary",
    category: "special_ability",
    icon: "📚",
    imageId: null,
    effects: { lyricism: 10, consistency: 12 },
    prepEffects: {
      highPrepBonus: 50,
      minPrepDays: 10,
    },
  },
  {
    id: "freestyle_genius",
    name: "FREESTYLE GENIUS",
    description: "Can freestyle segments without writing them first",
    fullEffectText:
      "Can freestyle segments without writing. +20% research efficiency. -25% choke chance on freestyles.",
    rarity: "legendary",
    category: "special_ability",
    icon: "🎤",
    imageId: null,
    effects: { adaptability: 20, wordplay: 10, chokeRisk: -25 },
    prepEffects: {
      canFreestyle: true,
      researchEfficiency: 20,
      lowPrepBonus: 15,
    },
  },
  {
    id: "angle_master",
    name: "ANGLE MASTER",
    description: "Finds devastating angles faster than anyone",
    fullEffectText: "+35% research prep efficiency. Great at finding unique angles.",
    rarity: "epic",
    category: "special_ability",
    icon: "🎯",
    imageId: null,
    effects: { creativity: 12, wordplay: 8 },
    prepEffects: {
      researchEfficiency: 35,
    },
  },
  {
    id: "battle_technician",
    name: "BATTLE TECHNICIAN",
    description: "Approaches prep like a science",
    fullEffectText: "+40% research, +25% writing efficiency. Balanced prep bonus.",
    rarity: "legendary",
    category: "special_ability",
    icon: "🔬",
    imageId: null,
    effects: { lyricism: 10, consistency: 10 },
    prepEffects: {
      researchEfficiency: 40,
      writingEfficiency: 25,
    },
  },
  {
    id: "multitasker",
    name: "MULTITASKER",
    description: "Good at juggling multiple prep activities",
    fullEffectText: "+10% all prep types. -2% choke. Good at juggling responsibilities.",
    rarity: "rare",
    category: "special_ability",
    icon: "🤹",
    imageId: null,
    effects: { adaptability: 8, chokeRisk: -2 },
    prepEffects: {
      researchEfficiency: 10,
      writingEfficiency: 10,
      rehearsalEfficiency: 10,
      restEfficiency: 10,
    },
  },
  {
    id: "time_management_expert",
    name: "TIME MANAGEMENT EXPERT",
    description: "Maximizes every prep day",
    fullEffectText: "+20% research, +15% writing/rehearsal, +10% rest efficiency. No stress from multiple battles.",
    rarity: "epic",
    category: "special_ability",
    icon: "📅",
    imageId: null,
    effects: { consistency: 10, stressPerDay: -2 },
    prepEffects: {
      researchEfficiency: 20,
      writingEfficiency: 15,
      rehearsalEfficiency: 15,
      restEfficiency: 10,
      noMultiBattleStress: true,
    },
  },
  {
    id: "consummate_professional",
    name: "CONSUMMATE PROFESSIONAL",
    description: "Treats every battle like a championship",
    fullEffectText: "+15% ALL prep types. -4% choke. The ultimate professional.",
    rarity: "legendary",
    category: "special_ability",
    icon: "💼",
    imageId: null,
    effects: { consistency: 15, chokeRisk: -4 },
    prepEffects: {
      researchEfficiency: 15,
      writingEfficiency: 15,
      rehearsalEfficiency: 15,
      restEfficiency: 15,
    },
  },
  {
    id: "consistent_grinder",
    name: "CONSISTENT GRINDER",
    description: "Shows up and puts in work every day",
    fullEffectText: "+10% all prep types. +15% consistency. The definition of reliable.",
    rarity: "rare",
    category: "special_ability",
    icon: "💪",
    imageId: null,
    effects: { consistency: 15 },
    prepEffects: {
      researchEfficiency: 10,
      writingEfficiency: 10,
      rehearsalEfficiency: 10,
      restEfficiency: 10,
    },
  },

  // SELF-AWARENESS & MEMORIZATION BADGES (6)
  {
    id: "self_aware",
    name: "SELF-AWARE",
    description: "Knows exactly when they're ready and when they're not",
    fullEffectText: "+3 Self-Awareness. Always knows their true readiness level. Lower comfort threshold.",
    rarity: "epic",
    category: "special_ability",
    icon: "🪞",
    imageId: null,
    effects: { selfAwareness: 3, chokeRisk: -5, consistency: 8 },
  },
  {
    id: "overconfident",
    name: "OVERCONFIDENT",
    description: "Always thinks they're ready, even when they're not",
    fullEffectText: "-3 Self-Awareness. Often misjudges readiness. Higher choke risk when underprepared.",
    rarity: "common",
    category: "special_ability",
    icon: "😎",
    imageId: null,
    effects: { selfAwareness: -3, chokeRisk: 10, stagePresence: 5 },
    isNegative: true,
    removable: true,
    removalCondition: "Choke in 2 battles (reality check)",
  },
  {
    id: "clutch_performer",
    name: "CLUTCH PERFORMER",
    description: "Rises to the occasion in pressure moments",
    fullEffectText: "-15% choke risk. +2 Self-Awareness in pressure situations. Comfort threshold lowered.",
    rarity: "legendary",
    category: "special_ability",
    icon: "🎯",
    imageId: null,
    effects: { selfAwareness: 2, chokeRisk: -15, resilience: 10 },
  },
  {
    id: "bars_on_lock",
    name: "BARS ON LOCK",
    description: "Once memorized, never forgotten",
    fullEffectText: "+15% rehearsal efficiency. Material stays locked in. Lower comfort threshold needed.",
    rarity: "epic",
    category: "special_ability",
    icon: "🔒",
    imageId: null,
    effects: { consistency: 12, chokeRisk: -8 },
    prepEffects: {
      rehearsalEfficiency: 15,
    },
  },
  {
    id: "overthinking",
    name: "OVERTHINKING",
    description: "Always feels underprepared even when ready",
    fullEffectText: "-2 Self-Awareness (underconfident). Needs extra rehearsal to feel safe. Actually performs well.",
    rarity: "common",
    category: "special_ability",
    icon: "🌀",
    imageId: null,
    effects: { selfAwareness: -2, consistency: 5, stressPerDay: 2 },
    isNegative: true,
    removable: true,
    removalCondition: "Win 3 battles with minimal stumbles",
  },
  {
    id: "gunslinger",
    name: "GUNSLINGER",
    description: "Comfortable performing with minimal prep - raw talent",
    fullEffectText: "Low comfort threshold. +20% effectiveness with under 50% memorization. High variance.",
    rarity: "epic",
    category: "special_ability",
    icon: "🔫",
    imageId: null,
    effects: { adaptability: 15, chokeRisk: 5, selfAwareness: -1 },
    prepEffects: {
      lowPrepBonus: 20,
    },
  },
]
