// AUTO-GENERATED by scripts/wire-badge-art.mjs — single source of truth for badge medallion art.
// Numbering recovered from the three generation contact sheets (raw images/badges/*);
// validated anchors: badge_046 = REBUTTAL KING, badge_054 = WELL RESEARCHED.
// Regenerate: node scripts/wire-badge-art.mjs

/** badge id -> medallion sprite path */
export const BADGE_ART: Record<string, string> = {
  "master_wordsmith": "/sprites/badges/badge_041.png", // MASTER WORDSMITH (art: WORDPLAY WIZARD)
  "punchline_king": "/sprites/badges/badge_038.png", // PUNCHLINE KING
  "technical_writer": "/sprites/badges/badge_022.png", // TECHNICAL WRITER (art: INTRICATE SCHEMES)
  "angle_assassin": "/sprites/badges/badge_001.png", // ANGLE ASSASSIN (art: ANGLES)
  "scheme_specialist": "/sprites/badges/badge_039.png", // SCHEME SPECIALIST
  "metaphor_master": "/sprites/badges/badge_040.png", // METAPHOR MASTER
  "rebuttal_king": "/sprites/badges/badge_046.png", // REBUTTAL KING
  "well_researched": "/sprites/badges/badge_054.png", // WELL RESEARCHED
  "storyteller": "/sprites/badges/badge_029.png", // STORYTELLER (art: STORYTELLING)
  "bar_god": "/sprites/badges/badge_050.png", // BAR GOD (art: PEN GAME ELITE)
  "multi_syllabic": "/sprites/badges/badge_053.png", // MULTI-SYLLABIC MASTER (art: MULTISYLLABIC MASTER)
  "haymaker_specialist": "/sprites/badges/badge_052.png", // HAYMAKER SPECIALIST (art: HARD-HITTING HAYMAKERS)
  "wordsmith": "/sprites/badges/badge_017.png", // WORDSMITH (art: WORDPLAY)
  "clever_writer": "/sprites/badges/badge_018.png", // CLEVER WRITER (art: WITTY WORDPLAY)
  "quotable": "/sprites/badges/badge_051.png", // QUOTABLE (art: QUOTABLE MACHINE)
  "layered_writer": "/sprites/badges/badge_048.png", // LAYERED WRITER (art: DOUBLE ENTENDRE EXPERT)
  "pocket_checker": "/sprites/badges/badge_003.png", // POCKET CHECKER (art: DISRESPECT)
  "flip_master": "/sprites/badges/badge_032.png", // FLIP MASTER (art: NAME FLIPS)
  "structure_savant": "/sprites/badges/badge_019.png", // STRUCTURE SAVANT (art: SCHEMES)
  "versatile_writer": "/sprites/badges/badge_049.png", // VERSATILE WRITER (art: UNPREDICTABLE)
  "crowd_favorite": "/sprites/badges/badge_076.png", // CROWD FAVORITE
  "showman": "/sprites/badges/badge_075.png", // SHOWMAN (art: CHARISMATIC)
  "energy_master": "/sprites/badges/badge_061.png", // ENERGY MASTER (art: EXPLOSIVE)
  "vocal_presence": "/sprites/badges/badge_074.png", // VOCAL PRESENCE (art: DYNAMIC RANGE)
  "ring_general": "/sprites/badges/badge_072.png", // RING GENERAL (art: STAGE DOMINATION)
  "aggressive_performer": "/sprites/badges/badge_056.png", // AGGRESSIVE PERFORMER (art: AGGRESSIVE)
  "crowd_reader": "/sprites/badges/badge_069.png", // CROWD READER (art: EMPATHETIC)
  "composed": "/sprites/badges/badge_063.png", // COMPOSED (art: NONCHALANT)
  "animated": "/sprites/badges/badge_067.png", // ANIMATED (art: IMPASSIONED)
  "intimidator": "/sprites/badges/badge_057.png", // INTIMIDATOR (art: MENACING)
  "mic_control": "/sprites/badges/badge_070.png", // MIC CONTROL (art: POWER STANCE)
  "stage_veteran": "/sprites/badges/badge_080.png", // STAGE VETERAN (art: RESPECTED VETERAN)
  "crowd_hyper": "/sprites/badges/badge_073.png", // CROWD HYPER (art: CROWD INTERACTION)
  "charismatic": "/sprites/badges/badge_075.png", // CHARISMATIC
  "tempo_master": "/sprites/badges/badge_058.png", // TEMPO MASTER (art: SPEED RAPPING)
  "physical_performer": "/sprites/badges/badge_071.png", // PHYSICAL PERFORMER (art: FLUID MOVEMENT)
  "voice_modulator": "/sprites/badges/badge_066.png", // VOICE MODULATOR (art: MELODIC)
  "crowd_silencer": "/sprites/badges/badge_068.png", // CROWD SILENCER (art: COLD)
  "moment_maker": "/sprites/badges/badge_077.png", // MOMENT MAKER (art: SHOW STEALER)
  "street_legend": "/sprites/badges/badge_014.png", // STREET LEGEND (art: OG BARS)
  "main_stage_ready": "/sprites/badges/badge_078.png", // MAIN STAGE READY (art: BIG STAGE PERFORMER)
  "respected_veteran": "/sprites/badges/badge_080.png", // RESPECTED VETERAN
  "hype_machine": "/sprites/badges/badge_013.png", // HYPE MACHINE (art: BRAGGADOCIOUS)
  "controversial": "/sprites/badges/badge_034.png", // CONTROVERSIAL
  "fan_favorite": "/sprites/badges/badge_076.png", // FAN FAVORITE (art: CROWD FAVORITE)
  "consistent_performer": "/sprites/badges/badge_044.png", // CONSISTENT PERFORMER (art: CONSISTENT WRITER)
  "headline_maker": "/sprites/badges/badge_034.png", // HEADLINE MAKER (art: CONTROVERSIAL)
  "aggressive_style": "/sprites/badges/badge_056.png", // AGGRESSIVE STYLE (art: AGGRESSIVE)
  "lyrical_purist": "/sprites/badges/badge_017.png", // LYRICAL PURIST (art: WORDPLAY)
  "entertainer": "/sprites/badges/badge_009.png", // ENTERTAINER (art: SLAPSTICK)
  "personals_specialist": "/sprites/badges/badge_002.png", // PERSONALS SPECIALIST (art: PERSONALS)
  "freestyle_artist": "/sprites/badges/badge_036.png", // FREESTYLE ARTIST (art: FREESTYLES)
  "gun_bar_specialist": "/sprites/badges/badge_020.png", // GUN BAR SPECIALIST (art: VIOLENT IMAGERY)
  "comedy_battler": "/sprites/badges/badge_004.png", // COMEDY BATTLER (art: COMEDY)
  "shock_value": "/sprites/badges/badge_035.png", // SHOCK VALUE
  "sports_bars": "/sprites/badges/badge_023.png", // SPORTS BARS KING (art: SPORTS REFERENCES)
  "pop_culture": "/sprites/badges/badge_024.png", // POP CULTURE MASTER (art: POP CULTURE REFERENCES)
  "battle_rapper": "/sprites/badges/badge_014.png", // TRADITIONAL BATTLE RAPPER (art: OG BARS)
  "poet": "/sprites/badges/badge_015.png", // POET (art: METAPHORS)
  "conscious_battler": "/sprites/badges/badge_028.png", // CONSCIOUS BATTLER (art: SOCIAL COMMENTARY)
  "actor": "/sprites/badges/badge_010.png", // ACTOR (art: CONCEPT BATTLES)
  "street_battler": "/sprites/badges/badge_012.png", // STREET BATTLER (art: STREET TALK)
  "choker": "/sprites/badges/badge_094.png", // CHOKER
  "ring_rust": "/sprites/badges/badge_089.png", // RING RUST (art: OUTDATED)
  "controversial_loss": "/sprites/badges/badge_105.png", // CONTROVERSIAL LOSS (art: SORE LOSER)
  "exposed": "/sprites/badges/badge_112.png", // EXPOSED (art: FAKE TOUGH GUY)
  "overhyped": "/sprites/badges/badge_096.png", // OVERHYPED
  "slumping": "/sprites/badges/badge_097.png", // SLUMPING (art: INCONSISTENT)
  "beef_distracted": "/sprites/badges/badge_107.png", // BEEF DISTRACTED (art: DRAMA STARTER)
  "burned_out": "/sprites/badges/badge_103.png", // BURNED OUT (art: ENERGY DRAINER)
  "predictable": "/sprites/badges/badge_086.png", // PREDICTABLE
  "photographic_memory": "/sprites/badges/badge_025.png", // PHOTOGRAPHIC MEMORY (art: HISTORICAL REFERENCES)
  "quick_writer": "/sprites/badges/badge_065.png", // QUICK WRITER (art: RAPID-FIRE)
  "team_player": "/sprites/badges/badge_069.png", // TEAM PLAYER (art: EMPATHETIC)
  "last_minute_larry": "/sprites/badges/badge_099.png", // LAST MINUTE LARRY (art: TIME WASTER)
  "preparation_monster": "/sprites/badges/badge_054.png", // PREPARATION MONSTER (art: WELL RESEARCHED)
  "freestyle_genius": "/sprites/badges/badge_042.png", // FREESTYLE GENIUS
  "angle_master": "/sprites/badges/badge_045.png", // ANGLE MASTER
  "battle_technician": "/sprites/badges/badge_022.png", // BATTLE TECHNICIAN (art: INTRICATE SCHEMES)
  "time_management_expert": "/sprites/badges/badge_055.png", // TIME MANAGEMENT EXPERT (art: WELL-TIMED HUMOR)
  "consummate_professional": "/sprites/badges/badge_080.png", // CONSUMMATE PROFESSIONAL (art: RESPECTED VETERAN)
  "consistent_grinder": "/sprites/badges/badge_044.png", // CONSISTENT GRINDER (art: CONSISTENT WRITER)
  "self_aware": "/sprites/badges/badge_007.png", // SELF-AWARE (art: SELF-DEPRECATING)
  "overconfident": "/sprites/badges/badge_115.png", // OVERCONFIDENT (art: EGO ISSUES)
  "clutch_performer": "/sprites/badges/badge_079.png", // CLUTCH PERFORMER
  "bars_on_lock": "/sprites/badges/badge_051.png", // BARS ON LOCK (art: QUOTABLE MACHINE)
  "gunslinger": "/sprites/badges/badge_020.png", // GUNSLINGER (art: VIOLENT IMAGERY)
}

/** UPPERCASE badge display-name -> medallion sprite path (style tags & legacy name lookups) */
export const BADGE_ART_BY_NAME: Record<string, string> = {
  "MASTER WORDSMITH": "/sprites/badges/badge_041.png",
  "PUNCHLINE KING": "/sprites/badges/badge_038.png",
  "TECHNICAL WRITER": "/sprites/badges/badge_022.png",
  "ANGLE ASSASSIN": "/sprites/badges/badge_001.png",
  "SCHEME SPECIALIST": "/sprites/badges/badge_039.png",
  "METAPHOR MASTER": "/sprites/badges/badge_040.png",
  "REBUTTAL KING": "/sprites/badges/badge_046.png",
  "WELL RESEARCHED": "/sprites/badges/badge_054.png",
  "STORYTELLER": "/sprites/badges/badge_029.png",
  "BAR GOD": "/sprites/badges/badge_050.png",
  "MULTI-SYLLABIC MASTER": "/sprites/badges/badge_053.png",
  "HAYMAKER SPECIALIST": "/sprites/badges/badge_052.png",
  "WORDSMITH": "/sprites/badges/badge_017.png",
  "CLEVER WRITER": "/sprites/badges/badge_018.png",
  "QUOTABLE": "/sprites/badges/badge_051.png",
  "LAYERED WRITER": "/sprites/badges/badge_048.png",
  "POCKET CHECKER": "/sprites/badges/badge_003.png",
  "FLIP MASTER": "/sprites/badges/badge_032.png",
  "STRUCTURE SAVANT": "/sprites/badges/badge_019.png",
  "VERSATILE WRITER": "/sprites/badges/badge_049.png",
  "CROWD FAVORITE": "/sprites/badges/badge_076.png",
  "SHOWMAN": "/sprites/badges/badge_075.png",
  "ENERGY MASTER": "/sprites/badges/badge_061.png",
  "VOCAL PRESENCE": "/sprites/badges/badge_074.png",
  "RING GENERAL": "/sprites/badges/badge_072.png",
  "AGGRESSIVE PERFORMER": "/sprites/badges/badge_056.png",
  "CROWD READER": "/sprites/badges/badge_069.png",
  "COMPOSED": "/sprites/badges/badge_063.png",
  "ANIMATED": "/sprites/badges/badge_067.png",
  "INTIMIDATOR": "/sprites/badges/badge_057.png",
  "MIC CONTROL": "/sprites/badges/badge_070.png",
  "STAGE VETERAN": "/sprites/badges/badge_080.png",
  "CROWD HYPER": "/sprites/badges/badge_073.png",
  "CHARISMATIC": "/sprites/badges/badge_075.png",
  "TEMPO MASTER": "/sprites/badges/badge_058.png",
  "PHYSICAL PERFORMER": "/sprites/badges/badge_071.png",
  "VOICE MODULATOR": "/sprites/badges/badge_066.png",
  "CROWD SILENCER": "/sprites/badges/badge_068.png",
  "MOMENT MAKER": "/sprites/badges/badge_077.png",
  "STREET LEGEND": "/sprites/badges/badge_014.png",
  "MAIN STAGE READY": "/sprites/badges/badge_078.png",
  "RESPECTED VETERAN": "/sprites/badges/badge_080.png",
  "HYPE MACHINE": "/sprites/badges/badge_013.png",
  "CONTROVERSIAL": "/sprites/badges/badge_034.png",
  "FAN FAVORITE": "/sprites/badges/badge_076.png",
  "CONSISTENT PERFORMER": "/sprites/badges/badge_044.png",
  "HEADLINE MAKER": "/sprites/badges/badge_034.png",
  "AGGRESSIVE STYLE": "/sprites/badges/badge_056.png",
  "LYRICAL PURIST": "/sprites/badges/badge_017.png",
  "ENTERTAINER": "/sprites/badges/badge_009.png",
  "PERSONALS SPECIALIST": "/sprites/badges/badge_002.png",
  "FREESTYLE ARTIST": "/sprites/badges/badge_036.png",
  "GUN BAR SPECIALIST": "/sprites/badges/badge_020.png",
  "COMEDY BATTLER": "/sprites/badges/badge_004.png",
  "SHOCK VALUE": "/sprites/badges/badge_035.png",
  "SPORTS BARS KING": "/sprites/badges/badge_023.png",
  "POP CULTURE MASTER": "/sprites/badges/badge_024.png",
  "TRADITIONAL BATTLE RAPPER": "/sprites/badges/badge_014.png",
  "POET": "/sprites/badges/badge_015.png",
  "CONSCIOUS BATTLER": "/sprites/badges/badge_028.png",
  "ACTOR": "/sprites/badges/badge_010.png",
  "STREET BATTLER": "/sprites/badges/badge_012.png",
  "CHOKER": "/sprites/badges/badge_094.png",
  "RING RUST": "/sprites/badges/badge_089.png",
  "CONTROVERSIAL LOSS": "/sprites/badges/badge_105.png",
  "EXPOSED": "/sprites/badges/badge_112.png",
  "OVERHYPED": "/sprites/badges/badge_096.png",
  "SLUMPING": "/sprites/badges/badge_097.png",
  "BEEF DISTRACTED": "/sprites/badges/badge_107.png",
  "BURNED OUT": "/sprites/badges/badge_103.png",
  "PREDICTABLE": "/sprites/badges/badge_086.png",
  "PHOTOGRAPHIC MEMORY": "/sprites/badges/badge_025.png",
  "QUICK WRITER": "/sprites/badges/badge_065.png",
  "TEAM PLAYER": "/sprites/badges/badge_069.png",
  "LAST MINUTE LARRY": "/sprites/badges/badge_099.png",
  "PREPARATION MONSTER": "/sprites/badges/badge_054.png",
  "FREESTYLE GENIUS": "/sprites/badges/badge_042.png",
  "ANGLE MASTER": "/sprites/badges/badge_045.png",
  "BATTLE TECHNICIAN": "/sprites/badges/badge_022.png",
  "TIME MANAGEMENT EXPERT": "/sprites/badges/badge_055.png",
  "CONSUMMATE PROFESSIONAL": "/sprites/badges/badge_080.png",
  "CONSISTENT GRINDER": "/sprites/badges/badge_044.png",
  "SELF-AWARE": "/sprites/badges/badge_007.png",
  "OVERCONFIDENT": "/sprites/badges/badge_115.png",
  "CLUTCH PERFORMER": "/sprites/badges/badge_079.png",
  "BARS ON LOCK": "/sprites/badges/badge_051.png",
  "GUNSLINGER": "/sprites/badges/badge_020.png",
}

/** badges with no medallion art yet — render emoji/initial fallback, queue for generation */
export const BADGE_ART_GAPS: string[] = [
  "camera_aware", // CAMERA AWARE (performance/common)
  "rising_star", // RISING STAR (reputation/common)
  "underdog", // UNDERDOG (reputation/rare)
  "gatekeeper", // GATEKEEPER (reputation/epic)
  "draw_power", // DRAW POWER (reputation/legendary)
  "viral_battler", // VIRAL BATTLER (reputation/epic)
  "peoples_champ", // PEOPLE'S CHAMPION (reputation/legendary)
  "underrated", // UNDERRATED (reputation/common)
  "rookie", // ROOKIE (milestone/common)
  "journeyman", // JOURNEYMAN (milestone/rare)
  "veteran", // VETERAN (milestone/epic)
  "legend", // LEGEND (milestone/legendary)
  "first_win", // FIRST VICTORY (milestone/common)
  "ten_wins", // TEN VICTORIES (milestone/common)
  "undefeated_streak", // UNDEFEATED (milestone/rare)
  "bounce_back", // BOUNCE BACK (milestone/common)
  "money_maker", // MONEY MAKER (milestone/epic)
  "world_traveler", // WORLD TRAVELER (milestone/rare)
  "new_york_king", // NEW YORK KING (city/epic)
  "la_legend", // LA LEGEND (city/epic)
  "chicago_champion", // CHICAGO CHAMPION (city/epic)
  "atlanta_ace", // ATLANTA ACE (city/epic)
  "detroit_destroyer", // DETROIT DESTROYER (city/epic)
  "east_coast_elite", // EAST COAST ELITE (region/legendary)
  "west_coast_warrior", // WEST COAST WARRIOR (region/legendary)
  "midwest_monster", // MIDWEST MONSTER (region/legendary)
  "south_sovereign", // SOUTH SOVEREIGN (region/legendary)
  "national_threat", // NATIONAL THREAT (region/legendary)
  "injured", // INJURED (special_ability/rare)
  "double_shift", // DOUBLE SHIFT (special_ability/legendary)
  "multitasker", // MULTITASKER (special_ability/rare)
  "overthinking", // OVERTHINKING (special_ability/common)
]

/** Resolve art for a badge by id or display name. */
export function badgeArt(idOrName?: string | null): string | undefined {
  if (!idOrName) return undefined
  return BADGE_ART[idOrName] ?? BADGE_ART_BY_NAME[idOrName.toUpperCase().trim()]
}
