import type { CSSProperties } from "react"
import cropsRaw from "./sprite-crops.json"

export type SpriteBox = { x: number; y: number; w: number; h: number }

// Map of web sprite path -> content bounding box (0..1 fractions of the canvas).
// Generated by scripts/audit-portrait-crops.ts (measures non-transparent pixel bounds via sharp).
const crops = cropsRaw as Record<string, SpriteBox>

export function getSpriteBox(url?: string): SpriteBox | null {
  if (!url) return null
  const clean = url.split("?")[0]
  return crops[clean] ?? null
}

/**
 * Inline style that makes a transparent-bg bust FILL its frame with the content
 * anchored to the bottom edge (character-select style) — never floating.
 *
 * The frame element must be `position:relative; overflow:hidden`. Works off the
 * measured content box; falls back to a sane bottom-anchored scale when unmeasured.
 */
export function portraitFillStyle(url?: string, opts: { targetH?: number; maxScale?: number } = {}): CSSProperties {
  const { targetH = 1.0, maxScale = 1.9 } = opts
  const box = getSpriteBox(url)

  if (!box) {
    return {
      position: "absolute",
      left: "50%",
      bottom: "-3%",
      width: "126%",
      height: "auto",
      maxWidth: "none",
      transform: "translateX(-50%)",
      imageRendering: "pixelated",
    }
  }

  const cx = box.x + box.w / 2 // content centre x (fraction)
  const scale = Math.min(maxScale, targetH / Math.max(0.15, box.h)) // fill content to targetH of frame
  const ty = (1 - (box.y + box.h)) * 100 // push content bottom down to the frame bottom
  const tx = -(cx - 0.5) * 100 // re-centre content horizontally

  return {
    position: "absolute",
    left: "50%",
    bottom: 0,
    height: "100%",
    width: "auto",
    maxWidth: "none",
    transformOrigin: "bottom center",
    transform: `translateX(-50%) translateX(${tx.toFixed(2)}%) translateY(${ty.toFixed(2)}%) scale(${scale.toFixed(3)})`,
    imageRendering: "pixelated",
  }
}
