-- Re-mapped league logo_url based on baked-in sprite labels (semantic match).
-- Generated by scripts/gen-icon-remap-migrations.mjs after scripts/remap-league-logos.mjs.

UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196070252/league_072.png' WHERE short_code = 'BBB';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196076327/league_050.png' WHERE short_code = 'BSL';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196065055/league_073.png' WHERE short_code = 'CCB';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196076327/league_051.png' WHERE short_code = 'FSY';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196086883/league_025.png' WHERE short_code = 'GBA';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764195933542/league_104.png' WHERE short_code = 'GIG';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196239271/league_005.png' WHERE short_code = 'IDW';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196239271/league_004.png' WHERE short_code = 'MIL';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196076327/league_049.png' WHERE short_code = 'MMA';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764195537197/league_110.png' WHERE short_code = 'MSA';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196239271/league_003.png' WHERE short_code = 'RTC';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764195526092/league_152.png' WHERE short_code = 'RWS';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196065055/league_078.png' WHERE short_code = 'SFA';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764195933542/league_103.png' WHERE short_code = 'SLP';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196076327/league_053.png' WHERE short_code = 'SRC';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764195528394/league_139.png' WHERE short_code = 'STC';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196239271/league_001.png' WHERE short_code = 'STF';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196065055/league_079.png' WHERE short_code = 'UWL';
UPDATE leagues SET logo_url = '/sprites/leagues/image_1764196086883/league_026.png' WHERE short_code = 'YGS';
