-- Backfill background_url and skyline_url on cities.
-- Sprites under /public/sprites/cities/{region}/{slug}-{day|dusk|night}.png
-- Generated by scripts/gen-city-sprite-migration.mjs (run after backfill-city-sprites.mjs).

UPDATE cities SET background_url = '/sprites/cities/south/atlanta-dusk.png', skyline_url = '/sprites/cities/south/atlanta-night.png' WHERE name = 'Atlanta';
UPDATE cities SET background_url = '/sprites/cities/midwest/chicago-dusk.png', skyline_url = '/sprites/cities/midwest/chicago-night.png' WHERE name = 'Chicago';
UPDATE cities SET background_url = '/sprites/cities/midwest/detroit-dusk.png', skyline_url = '/sprites/cities/midwest/detroit-night.png' WHERE name = 'Detroit';
UPDATE cities SET background_url = '/sprites/cities/south/houston-dusk.png', skyline_url = '/sprites/cities/south/houston-night.png' WHERE name = 'Houston';
UPDATE cities SET background_url = '/sprites/cities/west-coast/los-angeles-dusk.png', skyline_url = '/sprites/cities/west-coast/los-angeles-night.png' WHERE name = 'Los Angeles';
UPDATE cities SET background_url = '/sprites/cities/east-coast/new-york-city-dusk.png', skyline_url = '/sprites/cities/east-coast/new-york-city-night.png' WHERE name = 'New York City';
UPDATE cities SET background_url = '/sprites/cities/west-coast/oakland-dusk.png', skyline_url = '/sprites/cities/west-coast/oakland-night.png' WHERE name = 'Oakland';
UPDATE cities SET background_url = '/sprites/cities/east-coast/philadelphia-dusk.png', skyline_url = '/sprites/cities/east-coast/philadelphia-night.png' WHERE name = 'Philadelphia';
UPDATE cities SET background_url = '/sprites/cities/canada/toronto-dusk.png', skyline_url = '/sprites/cities/canada/toronto-night.png' WHERE name = 'Toronto';
